# Generated by Django 4.1 on 2022-09-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='todo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
