# Generated by Django 4.1.7 on 2023-02-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
        ('projects', '0002_project_requirements_project_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(help_text='Project contributors', related_name='contributors', to='users.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(help_text='Project description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='favorite',
            field=models.ManyToManyField(help_text='Favorite projects', related_name='favorites', to='users.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Project name', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(help_text='Project owner', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_status',
            field=models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=False, help_text='Public or private project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.CharField(help_text='Project requirements', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='todo',
            field=models.CharField(help_text='Project To Do list', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_flow_image',
            field=models.ImageField(blank=True, help_text='Project video', null=True, upload_to='user_flows/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wireframe',
            field=models.FileField(blank=True, help_text='Project image', null=True, upload_to='wireframes/'),
        ),
    ]
