# Generated by Django 4.1 on 2022-09-05 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pre_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public_status', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=1000)),
                ('wireframe', models.FileField(blank=True, null=True, upload_to='wireframes/')),
                ('user_flow_image', models.ImageField(blank=True, null=True, upload_to='user_flows/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributors', models.ManyToManyField(related_name='contributors', to='pre_login.user')),
                ('favorite', models.ManyToManyField(related_name='favorites', to='pre_login.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='pre_login.user')),
            ],
        ),
    ]
